export const AQUAMARINE_PROJECTILE_VISUAL_DELAY_MS = 200;
export const AQUAMARINE_WINDUP_MS = 110;
export const AQUAMARINE_RECOVERY_MS = 180;
export const AQUAMARINE_MIN_FLIGHT_MS = 35;
export const PROJECTILE_SPEED_GRID_PER_SEC = 15;
